// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeiJsydInDgltp8SUz-LSN9BMSF2pfn4Y',
    appId: '1:778646113271:web:d12c12213aa0ea88eefcf2',
    messagingSenderId: '778646113271',
    projectId: 'sidequest-afe17',
    authDomain: 'sidequest-afe17.firebaseapp.com',
    storageBucket: 'sidequest-afe17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWl1lkoLcFtVhCj1rNyg8Ld334onMBsrA',
    appId: '1:778646113271:android:50b62f39bf0462a3eefcf2',
    messagingSenderId: '778646113271',
    projectId: 'sidequest-afe17',
    storageBucket: 'sidequest-afe17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJt5qBpZSH4SQRwk1OI9HH9p_CoaoX4HM',
    appId: '1:778646113271:ios:a37c89a2f4d69be1eefcf2',
    messagingSenderId: '778646113271',
    projectId: 'sidequest-afe17',
    storageBucket: 'sidequest-afe17.firebasestorage.app',
    iosBundleId: 'com.example.sidequest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJt5qBpZSH4SQRwk1OI9HH9p_CoaoX4HM',
    appId: '1:778646113271:ios:a37c89a2f4d69be1eefcf2',
    messagingSenderId: '778646113271',
    projectId: 'sidequest-afe17',
    storageBucket: 'sidequest-afe17.firebasestorage.app',
    iosBundleId: 'com.example.sidequest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeiJsydInDgltp8SUz-LSN9BMSF2pfn4Y',
    appId: '1:778646113271:web:cd2f5ab63dae6e75eefcf2',
    messagingSenderId: '778646113271',
    projectId: 'sidequest-afe17',
    authDomain: 'sidequest-afe17.firebaseapp.com',
    storageBucket: 'sidequest-afe17.firebasestorage.app',
  );
}